/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practica_2_2;

import javax.swing.JOptionPane;

/**
 *
 * @author dvdor
 */
public class practica2_2 extends javax.swing.JFrame {

    /**
     * Creates new form practica2_2
     */
    public practica2_2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Saludito = new javax.swing.JLabel();
        Aceptar = new javax.swing.JButton();
        TextoEntrada2 = new javax.swing.JTextField();
        TextoPredet1 = new javax.swing.JLabel();
        TextoEntrada = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 350));
        setResizable(false);

        Saludito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica_2_2/saluda.png"))); // NOI18N
        Saludito.setText("jLabel1");

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        TextoEntrada2.setForeground(new java.awt.Color(102, 102, 102));
        TextoEntrada2.setText("Introduce su apellido");
        TextoEntrada2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoEntrada2ActionPerformed(evt);
            }
        });

        TextoPredet1.setText("Escriba el nombre y apellido del usuario");

        TextoEntrada.setForeground(new java.awt.Color(102, 102, 102));
        TextoEntrada.setText("Introduce su nombre");
        TextoEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoEntradaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(Saludito, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextoEntrada2)
                            .addComponent(TextoEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(Aceptar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(TextoPredet1)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(Saludito, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextoPredet1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextoEntrada2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Aceptar)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TextoEntrada2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoEntrada2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoEntrada2ActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        String nombre = TextoEntrada.getText();
        String apellido = TextoEntrada2.getText();
        
        if(nombre.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "No puede estar vacio.", "ERROR", JOptionPane.ERROR_MESSAGE);
            TextoEntrada.setText("");
            return;
        }
        
        if(nombre.length() < 5){
            javax.swing.JOptionPane.showMessageDialog(this, "Debe tener mas de 5 caractéres.", "ERROR", JOptionPane.ERROR_MESSAGE);
            TextoEntrada.setText("");
            return;
        }
        
        if(!nombre.matches("[a-zA-Z]+") ){
            javax.swing.JOptionPane.showMessageDialog(this, "Solo puede tener simbolos alfabéticos.", "ERROR", JOptionPane.ERROR_MESSAGE);
            TextoEntrada.setText("");
            return;
        }
        if(apellido.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "No puede estar vacio.", "ERROR", JOptionPane.ERROR_MESSAGE);
            TextoEntrada2.setText("");
            return;
        }
        
        if(apellido.length() < 5){
            javax.swing.JOptionPane.showMessageDialog(this, "Debe tener mas de 5 caractéres.", "ERROR", JOptionPane.ERROR_MESSAGE);
            TextoEntrada2.setText("");
            return;
        }
        
        if(!apellido.matches("[a-zA-Z]+")){
            javax.swing.JOptionPane.showMessageDialog(this, "Solo puede tener simbolos alfabéticos.", "ERROR", JOptionPane.ERROR_MESSAGE);
            TextoEntrada2.setText("");
            return;
        }
        
        JOptionPane.showMessageDialog(this,"Hola " + nombre + " " + apellido + "!", "Saludo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_AceptarActionPerformed

    private void TextoEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoEntradaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(practica2_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(practica2_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(practica2_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(practica2_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new practica2_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JLabel Saludito;
    private javax.swing.JTextField TextoEntrada;
    private javax.swing.JTextField TextoEntrada2;
    private javax.swing.JLabel TextoPredet1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
